services:
    zookeeper:
        image: quay.io/debezium/zookeeper:2.4
        ports: 
            - 2181:2181
            - 2888:2888
            - 3888:3888
    kafka:
        image: quay.io/debezium/kafka:2.4
        ports: 
            - 9092:9092
        links:
            - zookeeper
        environment:
            - ZOOKEEPER_CONNECT=zookeeper:2181
            - ADVERTISED_HOST_NAME=host.docker.internal
            