services:
    zookeeper:
        image: quay.io/debezium/zookeeper:2.4
        ports: 
            - 2181:2181
            - 2888:2888
            - 3888:3888
    kafka:
        image: quay.io/debezium/kafka:2.4
        ports: 
            - 9092:9092
        links:
            - zookeeper
        environment:
            - ZOOKEEPER_CONNECT=zookeeper:2181
            - ADVERTISED_HOST_NAME=host.docker.internal
    debezium:
        image: quay.io/debezium/connect:2.4
        ports: 
            - 8083:8083
        links:
            - kafka
        environment:
            - BOOTSTRAP_SERVERS=host.docker.internal:9092
            - OFFSET_STORAGE_TOPIC=my_connect_offsets
            - STATUS_STORAGE_TOPIC=my_connect_statuses
            - CONFIG_STORAGE_TOPIC=my_connect_configs
            - GROUP_ID=1